
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author NAIMI
 */
public class trans extends javax.swing.JFrame {

    /**
     * Creates new form trans
     */
    public trans() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        accnum = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        acctype = new javax.swing.JTextField();
        bal = new javax.swing.JTextField();
        amo = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        acc_num = new javax.swing.JTextField();
        fname = new javax.swing.JTextField();
        acc_type = new javax.swing.JTextField();
        baal = new javax.swing.JTextField();
        acc_tra = new javax.swing.JTextField();
        taramo = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        Trabal = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        acccnum = new javax.swing.JTextField();
        fulllname = new javax.swing.JTextField();
        accctype = new javax.swing.JTextField();
        ball = new javax.swing.JTextField();
        withbal = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        pinbal = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton12 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Transaction Details");

        jLabel2.setText("Account Number:");

        jLabel3.setText("Name:");

        jLabel5.setText("Account Type:");

        jLabel6.setText("Available Balance:");

        jLabel4.setText("Amount To Be Deposited:");

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        jButton1.setText("Get Details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Deposit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cancel");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(29, 29, 29)
                                .addComponent(amo, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(acctype, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(accnum, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jButton1))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(jButton2)
                        .addGap(56, 56, 56)
                        .addComponent(jButton3)
                        .addGap(57, 57, 57)
                        .addComponent(jButton4)))
                .addContainerGap(193, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel2))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(acctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(bal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(amo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(40, 40, 40))
        );

        jTabbedPane2.addTab("Deposit", jPanel2);

        jLabel7.setText("Account Number:");

        jLabel8.setText("Name:");

        jLabel9.setText("Account Type:");

        jLabel10.setText("Available Balance:");

        jLabel11.setText("Account Number to transfer:");

        jLabel12.setText("Transfer Amount:");

        jButton5.setText("Transfer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cancel");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        acc_num.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_numActionPerformed(evt);
            }
        });

        fname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fnameActionPerformed(evt);
            }
        });

        baal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baalActionPerformed(evt);
            }
        });

        acc_tra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acc_traActionPerformed(evt);
            }
        });

        jButton11.setText("Get Details");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jLabel19.setText("Enter Pin Number to transfer:");

        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(acc_num, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                .addComponent(fname)
                                .addComponent(acc_type, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(baal, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(acc_tra)
                                .addComponent(taramo, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Trabal, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jCheckBox2))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(jButton5)
                        .addGap(79, 79, 79)
                        .addComponent(jButton6)
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton11)))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acc_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(acc_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(baal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(acc_tra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(taramo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(Trabal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(22, 22, 22))
        );

        jTabbedPane2.addTab("Transfer", jPanel1);

        jLabel13.setText("Account Number:");

        jLabel14.setText("Name:");

        jLabel15.setText("Account Type:");

        jLabel16.setText("Available Balance:");

        jLabel17.setText("Amount to be withdrawn:");

        jButton8.setText("Withdraw");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Back");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Cancel");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jLabel18.setText("Enter Pin Number to withdraw:");

        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jButton12.setText("Get Details");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(accctype, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ball, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(acccnum, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                                .addComponent(fulllname))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(pinbal, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(withbal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jButton8)
                        .addGap(62, 62, 62)
                        .addComponent(jButton9)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton10))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButton12)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel13)
                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(acccnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton12)))
                                        .addGap(29, 29, 29)
                                        .addComponent(jLabel14))
                                    .addComponent(fulllname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27)
                                .addComponent(jLabel15))
                            .addComponent(accctype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addComponent(jLabel16))
                    .addComponent(ball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withbal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel18)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jCheckBox1)
                        .addComponent(pinbal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10))
                .addGap(30, 30, 30))
        );

        jTabbedPane2.addTab("Withdraw", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(286, 286, 286)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(75, 75, 75)
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
       /* int bal1=Integer.parseInt(bal.getText());
        int bal2=Integer.parseInt(amo.getText());
        bal1=bal1+bal2;
        String sum=String.valueOf(bal1);
        amo.setText(sum);
        String value=amo.getText();
        int val=Integer.parseInt(value);
        String value1=accnum.getText();
        int val1=Integer.parseInt(value1);*/
        int bal1=Integer.parseInt(baal.getText());
        int bal2=Integer.parseInt(taramo.getText());
        bal1=bal1-bal2;
        String sum=String.valueOf(bal1);
        //taramo.setText(sum);
        //String value=taramo.getText();
        int val=Integer.parseInt(sum);
        String value2=acc_num.getText();
        long val2=Long.parseLong(value2);
        String value1=acc_tra.getText();
        long val1=Long.parseLong(value1);
        String sql="update account set balance="+val+" where Account_Num="+val2+"";  //our account
        String sql1="update account set balance="+"balance"+"+"+bal2+" where Account_Num="+val1+""; //transfer account
        try{
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Bank","Bankdb","bindusri1234");
        PreparedStatement pst = con.prepareStatement(sql);
        PreparedStatement pst1 = con.prepareStatement(sql1);
       // PreparedStatement pst2 = con.prepareStatement(sql);
        String sql2="select account.account_num,customer.customer_id,pin from Account,acc_cus,customer where acc_cus.account_num=account.account_num and customer.customer_id=acc_cus.customer_id and account.account_num="+Long.parseLong(acc_num.getText())+"";
        String sql4="select account_num from account where account_num="+Long.parseLong(acc_tra.getText())+"";
        //System.out.println(Integer.parseInt(String.valueOf(pinbal.getPassword())));
        PreparedStatement pst2 = con.prepareStatement(sql2);
        ResultSet rs =pst2.executeQuery();
        PreparedStatement pst4 = con.prepareStatement(sql4);
        ResultSet rs1 =pst4.executeQuery();
        //int r=rs.getInt("pin");
        //int p1=pst.getInt(pin);
        int r = 0;
        long t=0;
        long a=0;
        long c=0;
        if(rs.next()){
            r=rs.getInt("pin");
            t=rs.getLong("account_num");
            c=rs.getLong("customer_id");
        }
        if(rs1.next()){
            a=rs1.getLong("account_num");
          //  System.out.println(Long.parseLong(acc_tra.getText()));
           // System.out.println(r);
        }
       // System.out.println(Integer.parseInt(String.valueOf(pinbal.getPassword())));
        if(Integer.parseInt(String.valueOf(Trabal.getPassword()))==r&&bal1>=bal2&&Long.parseLong(acc_num.getText())==t&&Long.parseLong(acc_tra.getText())==a){
            String sql3="insert into transfer(account_num,customer_id,pin,amount,transfer_accnum)values("+Long.parseLong(acc_num.getText())+","+c+","+r+","+bal2+","+Long.parseLong(acc_tra.getText())+")";
           // System.out.println(Long.parseLong(acc_num.getText()));
           // System.out.println(Long.parseLong(acc_tra.getText()));
            PreparedStatement pst3 = con.prepareStatement(sql3);
            pst3.executeUpdate();
            pst.executeUpdate();
            pst1.executeUpdate();
         // pst1.executeUpdate();
       // pst1.executeUpdate();
            JOptionPane.showMessageDialog(null, "Transferred Successfully!");
        }
        else if(Long.parseLong(acc_num.getText())!=t){
            JOptionPane.showMessageDialog(null,"Enter Correct Account Number");
        }
        else if(Long.parseLong(acc_tra.getText())!=a){
            JOptionPane.showMessageDialog(null,"Enter Correct Transfer Account Number");
        }
        else if(Integer.parseInt(String.valueOf(Trabal.getPassword()))!=r){
          JOptionPane.showMessageDialog(null, "Enter Correct Pin Number");
        }
        else if(bal1<bal2){
          JOptionPane.showMessageDialog(null, "No enough money in your account to Transfer!!");  
        }
        }
        catch(SQLException se){
      //Handle errors for JDBC
      //se.printStackTrace();
     JOptionPane.showMessageDialog(null,se);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void acc_numActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_numActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_numActionPerformed

    private void fnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fnameActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
       // System.exit(0);
       dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int bal1=Integer.parseInt(bal.getText());
        int bal2=Integer.parseInt(amo.getText());
        bal1=bal1+bal2;
        String sum=String.valueOf(bal1);
        //amo.setText(sum);
        //String value=sum.getText();
        long val=Long.parseLong(sum);
        String value1=accnum.getText();
        long val1=Long.parseLong(value1);
        String sql="update account set balance="+val+" where Account_Num="+val1+"";
        try{
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Bank","Bankdb","bindusri1234");
        PreparedStatement pst = con.prepareStatement(sql);
        String sql2="select account.account_num,customer.customer_id from account,customer,acc_cus where account.account_num=acc_cus.account_num and acc_cus.customer_ID=customer.customer_ID and account.account_num="+Long.parseLong(accnum.getText())+"";
        PreparedStatement pst2 = con.prepareStatement(sql2);
        ResultSet rs=pst2.executeQuery();
        long r=0;
        long t=0;
       // long p=0;
        if(rs.next()){
            r=rs.getLong("account_num");
            t=rs.getLong("customer_id");
           // p=rs.getLong("pin");
       
        // System.out.println(r);
        if(Long.parseLong(accnum.getText())==r){
        String sql1="insert into deposit(account_num,customer_id,amount)values("+val1+","+t+","+bal2+")";
        PreparedStatement pst1 = con.prepareStatement(sql1);
        pst1.executeUpdate();
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Deposited Successfully!");
        }
        
        else{
           JOptionPane.showMessageDialog(null, "Enter correct account number"); 
        }
        }
        }
        catch(SQLException se){
      //Handle errors for JDBC
     // se.printStackTrace();
    // JOptionPane.showMessageDialog(null,"Enter correct Account Number");
         System.out.println(se);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String sql="select * from account,customer,acc_cus where account.account_num=acc_cus.account_num and acc_cus.customer_ID=customer.customer_ID and account.Account_Num=?";
        try{
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Bank","Bankdb","bindusri1234");
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, accnum.getText());
        ResultSet rs=pst.executeQuery();
        //JOptionPane.showMessageDialog(null, "Deposited Successfully!");
        if(rs.next()){
            String add1=rs.getString("name");
            name.setText(add1);
            String add2=rs.getString("Account_type");
            acctype.setText(add2);
            String add3=rs.getString("Balance");
            bal.setText(add3);
            rs.close();
            pst.close();
        }
        else{
            JOptionPane.showMessageDialog(null, "Enter correct Account Number!");
        }
        }
        catch(SQLException se){
      //Handle errors for JDBC
     // se.printStackTrace();
     JOptionPane.showMessageDialog(null,"Enter correct Account Number");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dispose();
       // Intropage i=new Intropage();
        //i.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
       // System.exit(0);
       dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
      //  System.exit(0);
      dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
       // String sql="select * from account,customer where account.customer_ID=customer.customer_ID and Account_Num=?";
       String sql="select * from account,customer,acc_cus where account.account_num=acc_cus.account_num and acc_cus.customer_ID=customer.customer_ID and account.Account_Num=?";
       try{
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Bank","Bankdb","bindusri1234");
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, acc_num.getText());
        ResultSet rs=pst.executeQuery();
        //JOptionPane.showMessageDialog(null, "Deposited Successfully!");
        if(rs.next()){
            String add1=rs.getString("name");
            fname.setText(add1);
            String add2=rs.getString("Account_type");
            acc_type.setText(add2);
            String add3=rs.getString("Balance");
            baal.setText(add3);
            rs.close();
            pst.close();
        }
        else{
            JOptionPane.showMessageDialog(null, "Enter correct Account Number!");
        }
        }
       catch(SQLException se){
      //Handle errors for JDBC
     // se.printStackTrace();
     JOptionPane.showMessageDialog(null,"Enter correct Account Number");
       }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void baalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_baalActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        //String sql="select * from account,customer where account.customer_ID=customer.customer_ID and Account_Num=?";
        String sql="select * from account,customer,acc_cus where account.account_num=acc_cus.account_num and acc_cus.customer_ID=customer.customer_ID and account.Account_Num=?";
        try{
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Bank","Bankdb","bindusri1234");
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, acccnum.getText());
        ResultSet rs=pst.executeQuery();
        //JOptionPane.showMessageDialog(null, "Deposited Successfully!");
        if(rs.next()){
            String add1=rs.getString("name");
            fulllname.setText(add1);
            String add2=rs.getString("Account_type");
            accctype.setText(add2);
            String add3=rs.getString("Balance");
            ball.setText(add3);
            rs.close();
            pst.close();
        }
        else{
            JOptionPane.showMessageDialog(null, "Enter correct Account Number!");
        }
        }
        catch(SQLException se){
      //Handle errors for JDBC
     // se.printStackTrace();
     JOptionPane.showMessageDialog(null,"Enter correct Account Number");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
       // String sql="select * from account,customer,acc_cus where account.account_num=acc_cus.account_num and acc_cus.customer_ID=customer.customer_ID and account.Account_Num=?";
        int bal1=Integer.parseInt(ball.getText());
        int bal2=Integer.parseInt(withbal.getText());
        bal1=bal1-bal2;
        String sum=String.valueOf(bal1);
        //taramo.setText(sum);
        //String value=taramo.getText();
        int val=Integer.parseInt(sum);
        String value2=acccnum.getText();
        long val2=Long.parseLong(value2);
        //String value1.getText();
        //int val1=Integer.parseInt(value1);
        String sql="update account set balance="+sum+" where Account_Num="+val2+"";
       // String sql1="update account_creation set balance="+"balance"+"+"+bal2+" where Account_Num="+val1+"";
        try{
        Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/Bank","Bankdb","bindusri1234");
        PreparedStatement pst = con.prepareStatement(sql);
        String sql1="select account.account_num,customer.customer_id,pin from Account,customer,acc_cus where acc_cus.account_num=account.account_num and acc_cus.customer_id=customer.customer_id and account.account_num="+Long.parseLong(acccnum.getText())+"";
        //System.out.println(Integer.parseInt(String.valueOf(pinbal.getPassword())));
        PreparedStatement pst1 = con.prepareStatement(sql1);
        ResultSet rs =pst1.executeQuery();
        //int r=rs.getInt("pin");
        //int p1=pst.getInt(pin);
        int r = 0;
        long t=0;
        long c=0;
        if(rs.next()){
            r=rs.getInt("pin");
           // System.out.println(r);
            t=rs.getLong("account_num");
            c=rs.getLong("customer_id");
        }
        if(Integer.parseInt(String.valueOf(pinbal.getPassword()))==r&&bal1>=bal2&&Long.parseLong(acccnum.getText())==t){
            String sql2="insert into withdraw(account_num,customer_id,pin,amount)values("+t+","+c+","+r+","+bal2+")";
            PreparedStatement pst2 = con.prepareStatement(sql2);
            pst2.executeUpdate();
            pst.executeUpdate();
         // pst1.executeUpdate();
       // pst1.executeUpdate();
            JOptionPane.showMessageDialog(null, "Withdrawn Successfully!");
        }
      //  else if(Long.parseLong(acccnum.getText())!=t){
       //     JOptionPane.showMessageDialog(null,"Enter Correct Account Number");
        //}
         // JOptionPane.showMessageDialog(null, "Your Profile Updated!");
        else if(Integer.parseInt(String.valueOf(pinbal.getPassword()))!=r){
          JOptionPane.showMessageDialog(null, "Enter Correct Pin Number");
        }
       // PreparedStatement pst1 = con.prepareStatement(sql1);
        else if(bal1<bal2){
          JOptionPane.showMessageDialog(null, "No enough money in your account to Withdraw!!");  
        }
        }
        
        catch(SQLException se){
      //Handle errors for JDBC
     // se.printStackTrace();
         JOptionPane.showMessageDialog(null,se);}
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
                pinbal.setEchoChar((char)0);
            }
            else{
                pinbal.setEchoChar('*');
            }    
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void acc_traActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acc_traActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acc_traActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox2.isSelected()){
                Trabal.setEchoChar((char)0);
            }
            else{
                Trabal.setEchoChar('*');
            }   
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(trans.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new trans().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Trabal;
    private javax.swing.JTextField acc_num;
    private javax.swing.JTextField acc_tra;
    private javax.swing.JTextField acc_type;
    private javax.swing.JTextField acccnum;
    private javax.swing.JTextField accctype;
    private javax.swing.JTextField accnum;
    private javax.swing.JTextField acctype;
    private javax.swing.JTextField amo;
    private javax.swing.JTextField baal;
    private javax.swing.JTextField bal;
    private javax.swing.JTextField ball;
    private javax.swing.JTextField fname;
    private javax.swing.JTextField fulllname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField name;
    private javax.swing.JPasswordField pinbal;
    private javax.swing.JTextField taramo;
    private javax.swing.JTextField withbal;
    // End of variables declaration//GEN-END:variables
}
